#!/usr/bin/env python3
"""
Build the fixtures lookup for the app from the worldcupwallchart repo.

Source: worldcupwallchart/index.html, the G (group teams) and FX (fixtures)
data, itself from the official WCup_2026 spreadsheet. Maps the wallchart's
team names to this app's team codes and emits fixtures_array.js.

Output FIXTURES is keyed by the sorted code pair, e.g. "MEX|RSA":
  { d: "2026-06-11 19:00", v: "Mexico City", m: 1 }

Every pairing is validated to sit in the same group as in this app's data.
"""

import re
import json
from pathlib import Path

DATA = Path(__file__).resolve().parent
WALL = Path(r"C:\Users\abamf\Downloads\_wcwall_tmp\index.html")
TEAMFORM = DATA / "wc2026_team_form.json"
OUT = DATA / "fixtures_array.js"

# wallchart name -> this app's team code
NAME2CODE = {
    "Mexico": "MEX", "South Africa": "RSA", "Rep. of Korea": "KOR", "Czechia": "CZE",
    "Canada": "CAN", "Bosnia-Herzegovina": "BIH", "Qatar": "QAT", "Switzerland": "SUI",
    "Brazil": "BRA", "Morocco": "MAR", "Haiti": "HAI", "Scotland": "SCO",
    "USA": "USA", "Paraguay": "PAR", "Australia": "AUS", "Türkiye": "TUR",
    "Germany": "GER", "Curaçao": "CUW", "Ivory Coast": "CIV", "Ecuador": "ECU",
    "Netherlands": "NED", "Japan": "JPN", "Sweden": "SWE", "Tunisia": "TUN",
    "Belgium": "BEL", "Egypt": "EGY", "IR Iran": "IRN", "New Zealand": "NZL",
    "Spain": "ESP", "Cape Verde": "CPV", "Saudi Arabia": "KSA", "Uruguay": "URU",
    "France": "FRA", "Senegal": "SEN", "Iraq": "IRQ", "Norway": "NOR",
    "Argentina": "ARG", "Algeria": "ALG", "Austria": "AUT", "Jordan": "JOR",
    "Portugal": "POR", "DR Congo": "COD", "Uzbekistan": "UZB", "Colombia": "COL",
    "England": "ENG", "Croatia": "CRO", "Ghana": "GHA", "Panama": "PAN",
}


def main():
    html = WALL.read_text(encoding="utf-8")

    # ---- parse G: group -> [team names] ----
    g_block = re.search(r"const G = \{(.*?)\n\};", html, re.S).group(1)
    group_teams = {}
    for line in g_block.splitlines():
        m = re.match(r"\s*(\w):\{t:\[(.*?)\]", line)
        if not m:
            continue
        letter = m.group(1)
        names = [s.strip().strip("'\"") for s in m.group(2).split(",")]
        group_teams[letter] = names

    # ---- parse FX: tuples per group ----
    fx_block = re.search(r"const FX = \{(.*?)\n\};", html, re.S).group(1)
    tuple_rx = re.compile(r"\[(\d+),(\d+),(\d+),'([^']+)','([^']+)'\]")

    # my team data for validation
    teams = json.loads(TEAMFORM.read_text(encoding="utf-8"))["teams"]
    code2group = {t["c"]: t["g"] for t in teams}

    fixtures = {}
    errors = []
    count = 0
    for line in fx_block.splitlines():
        lm = re.match(r"\s*(\w):\[", line)
        if not lm:
            continue
        letter = lm.group(1)
        names = group_teams.get(letter, [])
        for t1, t2, mnum, dt, venue in tuple_rx.findall(line):
            i1, i2 = int(t1), int(t2)
            try:
                c1, c2 = NAME2CODE[names[i1]], NAME2CODE[names[i2]]
            except (IndexError, KeyError) as e:
                errors.append(f"group {letter} idx {t1},{t2}: {e}")
                continue
            # validate both in this group in my data
            if code2group.get(c1) != letter or code2group.get(c2) != letter:
                errors.append(f"{c1} v {c2} not both in group {letter} "
                              f"({code2group.get(c1)}/{code2group.get(c2)})")
            key = "|".join(sorted([c1, c2]))
            fixtures[key] = {"d": dt, "v": venue, "m": int(mnum)}
            count += 1

    # ---- emit js ----
    lines = ["// Auto-generated by build_fixtures.py from worldcupwallchart.",
             "// Group fixtures keyed by sorted team-code pair.",
             "const FIXTURES = {"]
    for key in sorted(fixtures, key=lambda k: fixtures[k]["m"]):
        fx = fixtures[key]
        lines.append(f'  "{key}":{{d:"{fx["d"]}",v:{json.dumps(fx["v"])},m:{fx["m"]}}},')
    lines.append("};")
    OUT.write_text("\n".join(lines), encoding="utf-8")

    print(f"fixtures parsed: {count}")
    print(f"unique pairings: {len(fixtures)}")
    print(f"output: {OUT.name} ({OUT.stat().st_size/1024:.1f} KB)")
    # show the opener and a couple
    for k in ["MEX|RSA", "CRO|ENG", "BRA|MAR"]:
        print(f"  {k}: {fixtures.get(k)}")
    if errors:
        print("ERRORS:")
        for e in errors[:20]:
            print("  -", e)
    else:
        print("VALIDATION: all pairings sit in the correct group")


if __name__ == "__main__":
    main()
