#!/usr/bin/env python3
"""
Build the PLAYERS array from the ScoutingStats World Cup player-stats API
(league 732, season 2025/26, club scope). Replaces the earlier FBref-based
player layer. Broader league coverage (1,163 players, all 48 nations,
including Turkish, Saudi, MLS etc.), so it reaches players the big-five FBref
set missed, e.g. Edson Álvarez at Fenerbahçe.

Source: ss_players_raw.json (harvested in-browser from the site's own API).
Fields per player kept minimal for the single-file app:
  t team code, n name, p position code, cl club,
  r risk (yc_p90*2 + fouls_p90), y yc_p90, f fouls_p90, ls low_sample
"""

import json
from pathlib import Path

DATA = Path(__file__).resolve().parent
SRC = DATA / "ss_club_full.json"
TEAMFORM = DATA / "wc2026_team_form.json"
OUT = DATA / "players_array.js"
LOW_SAMPLE_MINUTES = 450

# ScoutingStats ISO-3166 alpha-3 -> this app's FIFA-style code (only the diffs)
NAT_ALIAS = {"DZA": "ALG", "HTI": "HAI", "PRY": "PAR", "ZAF": "RSA"}
POS = {"Goalkeeper": "GK", "Defender": "DF", "Midfielder": "MF", "Attacker": "FW"}


def num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def main():
    raw = json.loads(SRC.read_text(encoding="utf-8"))
    players = raw["players"] if isinstance(raw, dict) and "players" in raw else raw

    teams = json.loads(TEAMFORM.read_text(encoding="utf-8"))["teams"]
    valid = {t["c"] for t in teams}

    out = []
    skipped = []
    for p in players:
        if p.get("__error"):
            continue
        code = NAT_ALIAS.get(p.get("nat"), p.get("nat"))
        if code not in valid:
            skipped.append(p.get("nat"))
            continue
        mins = num(p.get("min")) or 0
        yc = num(p.get("yc"))
        fc90 = num(p.get("fc90"))
        yc90 = round(yc / mins * 90, 3) if (yc is not None and mins > 0) else None
        risk = round((yc90 * 2) + fc90, 3) if (yc90 is not None and fc90 is not None) else None
        g90 = num(p.get("g90"))
        xg90 = num(p.get("xg90"))
        sot90 = num(p.get("sot90"))
        # goal threat: actual and expected goals per 90, weighted 60/40
        if g90 is not None and xg90 is not None:
            gt = round(0.6 * g90 + 0.4 * xg90, 3)
        elif g90 is not None:
            gt = g90
        else:
            gt = None
        gtot = p.get("g")
        out.append({
            "t": code, "n": p.get("n"), "p": POS.get(p.get("pos"), p.get("pos") or ""),
            "cl": p.get("cl") or "", "r": risk, "y": yc90, "f": fc90,
            "ls": (mins < LOW_SAMPLE_MINUTES),
            "g90": g90, "xg90": xg90, "sot90": sot90, "gt": gt,
            "g": (int(gtot) if isinstance(gtot, (int, float)) else None),
        })

    out.sort(key=lambda x: (x["t"], x["r"] is None, -(x["r"] or 0), x["n"] or ""))

    def v(x):
        if x is None:
            return "null"
        if isinstance(x, bool):
            return "true" if x else "false"
        if isinstance(x, str):
            return json.dumps(x, ensure_ascii=False)
        return str(x)

    lines = ["// Auto-generated by build_players_ss.py from the ScoutingStats",
             "// World Cup player-stats API (club scope, 2025/26). r = booking",
             "// risk (yc_p90*2 + fouls_p90); gt = goal threat (0.6*g90+0.4*xg90).",
             "const PLAYERS = ["]
    for p in out:
        lines.append("  {" + ",".join([
            f't:{v(p["t"])}', f'n:{v(p["n"])}', f'p:{v(p["p"])}', f'cl:{v(p["cl"])}',
            f'r:{v(p["r"])}', f'y:{v(p["y"])}', f'f:{v(p["f"])}', f'ls:{v(p["ls"])}',
            f'g90:{v(p["g90"])}', f'xg90:{v(p["xg90"])}', f'sot90:{v(p["sot90"])}', f'gt:{v(p["gt"])}',
            f'g:{v(p["g"])}',
        ]) + "},")
    lines.append("];")
    OUT.write_text("\n".join(lines), encoding="utf-8")

    scored = sum(1 for p in out if p["r"] is not None)
    from collections import Counter
    per = Counter(p["t"] for p in out)
    print(f"players: {len(out)}  scored: {scored}  size: {OUT.stat().st_size/1024:.1f} KB")
    print(f"skipped (unmapped nat): {Counter(skipped)}")
    print(f"teams covered: {len(per)}/48  min/team: {min(per.values())} max: {max(per.values())}")
    for c in ["MEX", "RSA", "ENG", "ARG", "BRA", "KSA"]:
        tps = sorted([p for p in out if p["t"] == c and p["r"] is not None], key=lambda x: -x["r"])[:3]
        print(f"  {c} ({per.get(c,0)}): " + ", ".join(f"{p['n']} {p['r']}" for p in tps))


if __name__ == "__main__":
    main()
