#!/usr/bin/env python3
"""
Build the INTL array (national-team form) from the ScoutingStats World Cup
hub, scope=country, season 2026. Per-player international fouls and cards per
90. Feeds the desk's player layer as an "International" toggle alongside the
club-form ranking.

Source: ss_intl_raw.json (harvested in-browser). Same risk formula as club:
risk = yc_p90*2 + fouls_p90. low_sample under 270 international minutes (3 caps).
"""

import json
from pathlib import Path

DATA = Path(__file__).resolve().parent
SRC = DATA / "ss_country_full.json"
TEAMFORM = DATA / "wc2026_team_form.json"
OUT = DATA / "intl_array.js"
LOW_MIN = 270

NAT_ALIAS = {"DZA": "ALG", "HTI": "HAI", "PRY": "PAR", "ZAF": "RSA"}
POS = {"Goalkeeper": "GK", "Defender": "DF", "Midfielder": "MF", "Attacker": "FW"}


def num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def main():
    raw = json.loads(SRC.read_text(encoding="utf-8"))
    players = raw["players"] if isinstance(raw, dict) and "players" in raw else raw
    valid = {t["c"] for t in json.loads(TEAMFORM.read_text(encoding="utf-8"))["teams"]}

    out = []
    for p in players:
        if p.get("__error"):
            continue
        code = NAT_ALIAS.get(p.get("nat"), p.get("nat"))
        if code not in valid:
            continue
        mins = num(p.get("min")) or 0
        yc = num(p.get("yc"))
        fc90 = num(p.get("fc90"))
        app = p.get("app")
        yc90 = round(yc / mins * 90, 3) if (yc is not None and mins > 0) else None
        risk = round((yc90 * 2) + fc90, 3) if (yc90 is not None and fc90 is not None) else None
        g90 = num(p.get("g90"))
        xg90 = num(p.get("xg90"))
        sot90 = num(p.get("sot90"))
        if g90 is not None and xg90 is not None:
            gt = round(0.6 * g90 + 0.4 * xg90, 3)
        elif g90 is not None:
            gt = g90
        else:
            gt = None
        out.append({
            "t": code, "n": p.get("n"),
            "p": POS.get(p.get("pos"), p.get("pos") or ""),
            "cl": (f"{app} caps" if app is not None else "") + (f" · {int(mins)} min" if mins else ""),
            "r": risk, "y": yc90, "f": fc90, "ls": (mins < LOW_MIN),
            "g90": g90, "xg90": xg90, "sot90": sot90, "gt": gt,
        })

    out.sort(key=lambda x: (x["t"], x["r"] is None, -(x["r"] or 0), x["n"] or ""))

    def v(x):
        if x is None:
            return "null"
        if isinstance(x, bool):
            return "true" if x else "false"
        if isinstance(x, str):
            return json.dumps(x, ensure_ascii=False)
        return str(x)

    lines = ["// Auto-generated by build_intl.py from ScoutingStats WC hub,",
             "// scope=country (national-team form, 2026). risk = yc_p90*2 + fouls_p90.",
             "const INTL = ["]
    for p in out:
        lines.append("  {" + ",".join([
            f't:{v(p["t"])}', f'n:{v(p["n"])}', f'p:{v(p["p"])}', f'cl:{v(p["cl"])}',
            f'r:{v(p["r"])}', f'y:{v(p["y"])}', f'f:{v(p["f"])}', f'ls:{v(p["ls"])}',
            f'g90:{v(p["g90"])}', f'xg90:{v(p["xg90"])}', f'sot90:{v(p["sot90"])}', f'gt:{v(p["gt"])}',
        ]) + "},")
    lines.append("];")
    OUT.write_text("\n".join(lines), encoding="utf-8")

    from collections import Counter
    per = Counter(p["t"] for p in out)
    scored = sum(1 for p in out if p["r"] is not None and not p["ls"])
    print(f"intl players: {len(out)}  scored(>={LOW_MIN}min): {scored}  size: {OUT.stat().st_size/1024:.1f} KB")
    print(f"teams covered: {len(per)}/48")
    missing = sorted({t for t in valid} - set(per))
    if missing:
        print("teams with no intl rows:", missing)
    for c in ["MEX", "RSA", "ENG", "BRA", "ARG"]:
        tps = sorted([p for p in out if p["t"] == c and p["r"] is not None and not p["ls"]], key=lambda x: -x["r"])[:3]
        print(f"  {c}: " + ", ".join(f"{p['n']} {p['r']}" for p in tps))


if __name__ == "__main__":
    main()
