#!/usr/bin/env python3
"""
Build the compact PLAYERS array for the app's per-fixture player layer.

Reads wc2026_squad_club_form.csv (1,248 confirmed squad players, with
club-form booking risk for the 484 in covered leagues) and emits
players_array.js holding a PLAYERS const keyed by team code.

Fields kept minimal for a single-file app:
  t  team code        n  player name       p  squad position
  cl club             r  risk_score|null   y  club_yc_per90|null
  f  club_fouls_per90|null                 ls low_sample (true/false/null)
"""

import csv
import json
from pathlib import Path

DATA = Path(__file__).resolve().parent
SRC = DATA / "wc2026_squad_club_form.csv"
OUT = DATA / "players_array.js"


def numornull(v):
    if v in (None, "", "null"):
        return None
    try:
        f = float(v)
        return int(f) if f == int(f) else round(f, 3)
    except (TypeError, ValueError):
        return None


def main():
    players = []
    with open(SRC, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            risk = numornull(row.get("risk_score"))
            players.append({
                "t": row["code"],
                "n": row["player_name"],
                "p": row.get("squad_pos") or "",
                "cl": row.get("club") or "",
                "r": risk,
                "y": numornull(row.get("club_yc_per90")),
                "f": numornull(row.get("club_fouls_per90")),
                "ls": (None if row.get("low_sample") in (None, "", "null")
                       else (row.get("low_sample") == "yes")),
            })

    # stable order: team code, then risk desc (nulls last), then name
    players.sort(key=lambda x: (x["t"], x["r"] is None, -(x["r"] or 0), x["n"]))

    lines = ["// Auto-generated by build_players_array.py from",
             "// wc2026_squad_club_form.csv. Risk is club-form only:",
             "// risk = club_yc_per90*2 + club_fouls_per90. null where the",
             "// player's league is outside the club dataset (big-5 only).",
             "const PLAYERS = ["]
    for p in players:
        def v(x):
            return "null" if x is None else (json.dumps(x, ensure_ascii=False)
                                             if isinstance(x, str) else
                                             ("true" if x is True else
                                              "false" if x is False else str(x)))
        lines.append("  {" + ",".join([
            f't:{v(p["t"])}', f'n:{v(p["n"])}', f'p:{v(p["p"])}',
            f'cl:{v(p["cl"])}', f'r:{v(p["r"])}', f'y:{v(p["y"])}',
            f'f:{v(p["f"])}', f'ls:{v(p["ls"])}',
        ]) + "},")
    lines.append("];")
    OUT.write_text("\n".join(lines), encoding="utf-8")

    # report
    total = len(players)
    scored = sum(1 for p in players if p["r"] is not None)
    from collections import Counter
    per_team = Counter(p["t"] for p in players)
    scored_per_team = Counter(p["t"] for p in players if p["r"] is not None)
    print(f"players: {total}")
    print(f"with club-form risk: {scored} ({100*scored/total:.1f}%)")
    print(f"output size: {OUT.stat().st_size/1024:.1f} KB")
    print("teams:", len(per_team))
    # sample: top 3 risk players for a few teams
    for code in ["ENG", "ARG", "MEX", "RSA", "BRA"]:
        tps = sorted([p for p in players if p["t"] == code and p["r"] is not None],
                     key=lambda x: -x["r"])[:3]
        s = ", ".join(f"{p['n']} {p['r']}" for p in tps) or "no club data"
        print(f"  {code} ({scored_per_team[code]}/{per_team[code]}): {s}")


if __name__ == "__main__":
    main()
