#!/usr/bin/env python3
"""
Build FD_STANDINGS (live World Cup group tables) for the WC desk from the
football-data.org harvest. Maps football-data TLA codes to this desk's team
codes and flags (from wc2026_team_form.json). Output: fd_standings.js.

Refresh: re-harvest /v4/competitions/WC/standings with the API token (kept in
a gitignored .env, never committed) into football_data_wc.json, then re-run.
"""
import json
from pathlib import Path

DATA = Path(__file__).resolve().parent
SRC = DATA / "football_data_wc.json"
TEAMFORM = DATA / "wc2026_team_form.json"
OUT = DATA / "fd_standings.js"

# football-data TLA -> this desk's team code (only the differences)
TLA_ALIAS = {}


def main():
    d = json.loads(SRC.read_text(encoding="utf-8"))
    teams = json.loads(TEAMFORM.read_text(encoding="utf-8"))["teams"]
    by_code = {t["c"]: t for t in teams}
    # also index desk teams by uppercased name for fallback matching
    by_name = {t["n"].lower(): t for t in teams}

    groups = []
    unmapped = []
    for g in d.get("standings", []):
        if g.get("type") != "TOTAL":
            continue
        rows = []
        for r in g["table"]:
            tla = r["team"]["tla"]
            code = TLA_ALIAS.get(tla, tla)
            dt = by_code.get(code) or by_name.get(r["team"]["name"].lower())
            if not dt:
                unmapped.append((tla, r["team"]["name"]))
                flag, name, code = "", r["team"]["name"], tla
            else:
                flag, name, code = dt["f"], dt["n"], dt["c"]
            rows.append({"c": code, "f": flag, "n": name, "p": r["playedGames"],
                         "w": r["won"], "d": r["draw"], "l": r["lost"],
                         "gf": r["goalsFor"], "ga": r["goalsAgainst"],
                         "gd": r["goalDifference"], "pts": r["points"]})
        groups.append({"g": g["group"].replace("Group ", ""), "rows": rows})

    def js(x):
        return json.dumps(x, ensure_ascii=False)

    lines = ["// Auto-generated by build_fd_standings.py from football-data.org.",
             "// Live World Cup group tables. Refresh by re-harvesting standings.",
             f"const FD_UPDATED={js(d.get('updatedAt') or d.get('matches',[{}])[0].get('lastUpdated','') if d.get('matches') else '')};",
             "const FD_STANDINGS=["]
    for g in groups:
        rws = ",".join("{" + ",".join([
            f'c:{js(r["c"])}', f'f:{js(r["f"])}', f'n:{js(r["n"])}',
            f'p:{r["p"]}', f'w:{r["w"]}', f'd:{r["d"]}', f'l:{r["l"]}',
            f'gf:{r["gf"]}', f'ga:{r["ga"]}', f'gd:{r["gd"]}', f'pts:{r["pts"]}',
        ]) + "}" for r in g["rows"])
        lines.append(f'  {{g:{js(g["g"])},rows:[{rws}]}},')
    lines.append("];")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"groups: {len(groups)}  rows: {sum(len(g['rows']) for g in groups)}  size: {OUT.stat().st_size/1024:.1f} KB")
    if unmapped:
        print("UNMAPPED tla->name:", unmapped)
    else:
        print("all teams mapped to desk codes/flags")
    # show group A
    a = next((g for g in groups if g["g"] == "A"), None)
    if a:
        for r in a["rows"]:
            print(f"   {r['c']} {r['n']:<16} P{r['p']} {r['pts']}pts GD{r['gd']:+d}")


if __name__ == "__main__":
    main()
