#!/usr/bin/env python3
"""
Build live World Cup data blocks from the football-data.org harvest:
  FD_STANDINGS  group tables (also via build_fd_standings.py)
  FD_RESULTS    finished-match scores keyed by sorted team-code pair
  FD_KNOCKOUT   the knockout bracket (round, kickoff, teams, score)

Output: fd_extra.js (FD_RESULTS + FD_KNOCKOUT). Refresh by re-harvesting
/v4/competitions/WC/matches with the token in the gitignored .env, then re-run.
"""
import json
from pathlib import Path

DATA = Path(__file__).resolve().parent
SRC = DATA / "football_data_wc.json"
TEAMFORM = DATA / "wc2026_team_form.json"
OUT = DATA / "fd_extra.js"
TLA_ALIAS = {}
STAGE = {"LAST_32": "Round of 32", "LAST_16": "Round of 16",
         "QUARTER_FINALS": "Quarter-finals", "SEMI_FINALS": "Semi-finals",
         "THIRD_PLACE": "Third place", "FINAL": "Final"}
ORDER = ["LAST_32", "LAST_16", "QUARTER_FINALS", "SEMI_FINALS", "THIRD_PLACE", "FINAL"]


def main():
    d = json.loads(SRC.read_text(encoding="utf-8"))
    teams = json.loads(TEAMFORM.read_text(encoding="utf-8"))["teams"]
    by_code = {t["c"]: t for t in teams}
    by_name = {t["n"].lower(): t for t in teams}

    def desk(tla, name):
        code = TLA_ALIAS.get(tla, tla)
        t = by_code.get(code) or by_name.get((name or "").lower())
        if t:
            return t["c"], t["f"], t["n"]
        return (code or None), "", (name or "")

    results = {}      # sorted code pair -> "H-A"
    knockout = []
    for m in d["matches"]:
        ht, at = m["homeTeam"], m["awayTeam"]
        ft = m["score"]["fullTime"]
        if m["stage"] == "GROUP_STAGE":
            if m["status"] == "FINISHED" and ht["tla"] and at["tla"]:
                hc, _, _ = desk(ht["tla"], ht["name"])
                ac, _, _ = desk(at["tla"], at["name"])
                a, b = sorted([hc, ac])
                s = f'{ft["home"]}-{ft["away"]}' if hc == a else f'{ft["away"]}-{ft["home"]}'
                results["|".join([a, b])] = s
        else:
            hc, hf, hn = desk(ht["tla"], ht["name"]) if ht["tla"] else (None, "", None)
            ac, af, an = desk(at["tla"], at["name"]) if at["tla"] else (None, "", None)
            sc = (f'{ft["home"]}-{ft["away"]}' if m["status"] == "FINISHED" and ft["home"] is not None else None)
            knockout.append({
                "st": m["stage"], "d": m["utcDate"].replace("T", " ")[:16],
                "hc": hc, "hf": hf, "hn": hn, "ac": ac, "af": af, "an": an,
                "sc": sc, "status": m["status"],
                # also bake group-stage knockout results into results map when teams known
            })
            if m["status"] == "FINISHED" and hc and ac and ft["home"] is not None:
                a, b = sorted([hc, ac])
                s = f'{ft["home"]}-{ft["away"]}' if hc == a else f'{ft["away"]}-{ft["home"]}'
                results["|".join([a, b])] = s
    knockout.sort(key=lambda k: (ORDER.index(k["st"]) if k["st"] in ORDER else 9, k["d"]))

    def js(x):
        return json.dumps(x, ensure_ascii=False)

    lines = ["// Auto-generated by build_fd.py from football-data.org.",
             "// FD_RESULTS: finished scores by sorted team-code pair (auto-merged",
             "// into RESULTS, never overriding manual entries). FD_KNOCKOUT: bracket.",
             "const FD_RESULTS=" + js(results) + ";",
             "const FD_STAGE_LABELS=" + js(STAGE) + ";",
             "const FD_KNOCKOUT=["]
    for k in knockout:
        lines.append("  {" + ",".join([
            f'st:{js(k["st"])}', f'd:{js(k["d"])}',
            f'hc:{js(k["hc"])}', f'hf:{js(k["hf"])}', f'hn:{js(k["hn"])}',
            f'ac:{js(k["ac"])}', f'af:{js(k["af"])}', f'an:{js(k["an"])}',
            f'sc:{js(k["sc"])}', f'status:{js(k["status"])}',
        ]) + "},")
    lines.append("];")
    OUT.write_text("\n".join(lines), encoding="utf-8")

    fin = sum(1 for v in results.values())
    played_ko = sum(1 for k in knockout if k["sc"])
    print(f"FD_RESULTS finished: {fin}  FD_KNOCKOUT: {len(knockout)} ({played_ko} played)  size: {OUT.stat().st_size/1024:.1f} KB")
    print("results sample:", dict(list(results.items())[:4]))
    from collections import Counter
    print("knockout rounds:", Counter(k["st"] for k in knockout))


if __name__ == "__main__":
    main()
