#!/usr/bin/env python3
"""
Build live-tournament discipline blocks for the WC desk from the post-match
card data in the WC26 Discipline Dashboard (D.cards) plus its MATCH_REF map
(referee per match, sourced from football-data.org).

Outputs tourn_data.js with:
  TOURN_TEAMS    {code:{y,r}}            cards collected per team this tournament
  TOURN_PLAYERS  {code:{surname:{y,r}}}  per-player bookings, keyed by surname
  TOURN_REFS     [{n,m,y,r,cpm}]         referee strictness (cards per match)
  TOURN_MATCHES  count of matches the data covers
"""
import json, re, unicodedata
from pathlib import Path

DATA = Path(__file__).resolve().parent
DASH = Path(r"C:\Users\abamf\Downloads\WC26 stats\WC26-Discipline-Dashboard.html")
TEAMFORM = DATA / "wc2026_team_form.json"
OUT = DATA / "tourn_data.js"


def norm(s):
    s = "".join(c for c in unicodedata.normalize("NFKD", s or "") if not unicodedata.combining(c)).lower().strip()
    return re.sub(r"[^a-z0-9 ]", "", s)


def teamkey(n):
    x = norm(n)
    if "ivoir" in x or "ivory" in x: return "ivory"
    if "turk" in x: return "turkiye"
    if "verde" in x: return "capeverde"
    if "korea" in x: return "korea"
    if "bosnia" in x: return "bosnia"
    if "iran" in x: return "iran"
    if x in ("usa", "united states"): return "usa"
    if "congo" in x: return "congo"
    if "czech" in x: return "czech"
    return x.replace(" ", "")


def main():
    html = DASH.read_text(encoding="utf-8")
    cards = json.loads(re.search(r'"cards":\s*(\[.*?\]),\s*"matches"', html, re.S).group(1))
    mr_block = re.search(r"const MATCH_REF=\{(.*?)\};", html, re.S).group(1)
    match_ref = {int(k): v for k, v in re.findall(r'(\d+):"([^"]*)"', mr_block)}

    teams = json.loads(TEAMFORM.read_text(encoding="utf-8"))["teams"]
    code_by_key = {teamkey(t["n"]): t["c"] for t in teams}

    tteams, tplayers = {}, {}
    unmapped = set()
    for c in cards:
        code = code_by_key.get(teamkey(c["team"]))
        if not code:
            unmapped.add(c["team"]); continue
        isY = c["card"] == "Yellow"
        tt = tteams.setdefault(code, {"y": 0, "r": 0})
        tt["y" if isY else "r"] += 1
        full = norm(c["player"])  # full normalised name, avoids same-surname mix-ups
        if full:
            pp = tplayers.setdefault(code, {}).setdefault(full, {"y": 0, "r": 0})
            pp["y" if isY else "r"] += 1

    # referees
    ragg = {}
    for mn, rf in match_ref.items():
        ragg.setdefault(rf, {"n": rf, "m": 0, "y": 0, "r": 0})["m"] += 1
    for c in cards:
        rf = match_ref.get(str(c["match"])) or match_ref.get(int(c["match"]))
        if not rf:
            continue
        ragg[rf]["y" if c["card"] == "Yellow" else "r"] += 1
    refs = sorted(ragg.values(), key=lambda x: -((x["y"] + x["r"]) / x["m"]))

    def js(x):
        return json.dumps(x, ensure_ascii=False)

    nmatch = len({c["match"] for c in cards} | set(int(k) for k in match_ref))
    lines = [
        "// Auto-generated by build_tourn.py from the WC26 Discipline Dashboard",
        "// (post-match card data) + MATCH_REF (referees via football-data.org).",
        f"const TOURN_MATCHES={nmatch};",
        "const TOURN_TEAMS=" + js(tteams) + ";",
        "const TOURN_PLAYERS=" + js(tplayers) + ";",
        "const TOURN_REFS=[" + ",".join(
            "{" + f'n:{js(r["n"])},m:{r["m"]},y:{r["y"]},rc:{r["r"]},cpm:{round((r["y"]+r["r"])/r["m"],2)}' + "}"
            for r in refs) + "];",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"teams: {len(tteams)}  players(teams): {len(tplayers)}  refs: {len(refs)}  matches: {nmatch}")
    print(f"size: {OUT.stat().st_size/1024:.1f} KB")
    if unmapped:
        print("UNMAPPED teams:", unmapped)
    # sanity
    print("top ref:", refs[0])
    print("MEX players:", tplayers.get("MEX"))
    print("RSA players:", tplayers.get("RSA"))


if __name__ == "__main__":
    main()
