#!/usr/bin/env python3
"""
Sync the generated data files into index.html's inline copies.

index.html embeds fd_standings.js (FD_UPDATED + FD_STANDINGS) and
fd_extra.js (FD_RESULTS + FD_STAGE_LABELS + FD_KNOCKOUT) verbatim; this
replaces those inline blocks with the current file contents so a data
refresh is: build_espn.py && sync_inline.py. Idempotent — running it when
nothing changed leaves index.html byte-identical.
"""
import re, sys
from pathlib import Path

DATA = Path(__file__).resolve().parent
INDEX = DATA.parent / "index.html"

BLOCKS = [
    # (data file, regex spanning the inline block it replaces)
    (DATA / "fd_standings.js",
     re.compile(r"// Auto-generated by build_(?:fd_standings|espn)\.py[^\n]*\n(?:.*?\n)?const FD_UPDATED=.*?const FD_STANDINGS=\[.*?\n\];", re.S)),
    (DATA / "fd_extra.js",
     re.compile(r"// Auto-generated by build_(?:fd|espn)\.py[^\n]*\n(?:// .*?\n)*const FD_RESULTS=.*?const FD_KNOCKOUT=\[.*?\n\];", re.S)),
]


def main():
    html = INDEX.read_text(encoding="utf-8")
    for path, pat in BLOCKS:
        content = path.read_text(encoding="utf-8").rstrip("\n")
        hits = pat.findall(html)
        if len(hits) != 1:
            sys.exit(f"ERROR: expected exactly 1 inline block for {path.name}, found {len(hits)}")
        html = pat.sub(lambda _: content, html, count=1)
    if html != INDEX.read_text(encoding="utf-8"):
        INDEX.write_text(html, encoding="utf-8")
        print("index.html inline blocks updated")
    else:
        print("index.html already in sync")


if __name__ == "__main__":
    main()
